name: NSE Corporate Actions Daily Run

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at 12:00 UTC (5:30 PM IST)
  workflow_dispatch:      # allows manual runs
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install git+https://github.com/browser-use/browser-use.git
          pip install -r requirements.txt
          
      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium
          python -m playwright install-deps
          
      - name: Run script  
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python main.py
        
      - name: Upload CSV Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-csv-files
          path: data/